name: scaffold_claim

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
  # Give misbehaving naughty babies a New Year's blessing~
  # Crontab表达式转义 https://crontab.guru/
  schedule:
    - cron: "5 4,8,0 * * *"
    - cron: "3 2 * * 6"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      # 下载依赖，如驱动器和 YOLOv4 model。
      - name: Scaffold Install
        run: |
          echo -e "EMAIL: ${{secrets.EPIC_EMAIL}}\nPASSWORD: ${{secrets.EPIC_PASSWORD}}" > src/config.yaml
          cd src && python main.py install

      # 五分钟搬空免费商店。
      - name: Scaffold Claim
        run: |
          export LANG=zh_CN.UTF8
          cd src && python main.py claim
